LANGUAGE_NAMES = {
    "en": ("English", "Latin"),
    "hi": ("Hindi", "Devanagari"),
    "es": ("Spanish", "Latin"),
    "fr": ("French", "Latin"),
    "de": ("German", "Latin"),
    "ar": ("Arabic", "Arabic"),
    "zh": ("Chinese", "Chinese characters"),
    "ja": ("Japanese", "Japanese"),
    "pt": ("Portuguese", "Latin"),
    "ur": ("Urdu", "Nastaliq/Urdu"),
    "bn": ("Bengali", "Bengali"),
    "te": ("Telugu", "Telugu"),
    "mr": ("Marathi", "Devanagari"),
    "ta": ("Tamil", "Tamil"),
    "gu": ("Gujarati", "Gujarati"),
    "kn": ("Kannada", "Kannada"),
    "ml": ("Malayalam", "Malayalam"),
    "pa": ("Punjabi", "Gurmukhi"),
}